"""add authors column to publications

Revision ID: 281b08784a7e
Revises: 4e6b2a896a36
Create Date: 2026-07-19 01:45:47.609199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281b08784a7e'
down_revision: Union[str, Sequence[str], None] = '4e6b2a896a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('authors', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'authors')
    # ### end Alembic commands ###
