"""add min_experience to funding opportunities

Revision ID: 28504bde276d
Revises: a5ec726586f7
Create Date: 2026-07-16 22:14:39.834555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28504bde276d'
down_revision: Union[str, Sequence[str], None] = 'a5ec726586f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funding_opportunities', sa.Column('min_experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funding_opportunities', 'min_experience')
    # ### end Alembic commands ###
