"""create patents table

Revision ID: 52067cdd1d7b
Revises: 281b08784a7e
Create Date: 2026-08-02 16:38:05.455320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52067cdd1d7b'
down_revision: Union[str, Sequence[str], None] = '281b08784a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('patent_number', sa.String(length=100), nullable=False),
    sa.Column('inventors', sa.Text(), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=False),
    sa.Column('technology_area', sa.String(length=150), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patents_id'), 'patents', ['id'], unique=False)
    op.create_index(op.f('ix_patents_patent_number'), 'patents', ['patent_number'], unique=True)
    op.create_index(op.f('ix_patents_status'), 'patents', ['status'], unique=False)
    op.create_index(op.f('ix_patents_technology_area'), 'patents', ['technology_area'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patents_technology_area'), table_name='patents')
    op.drop_index(op.f('ix_patents_status'), table_name='patents')
    op.drop_index(op.f('ix_patents_patent_number'), table_name='patents')
    op.drop_index(op.f('ix_patents_id'), table_name='patents')
    op.drop_table('patents')
    # ### end Alembic commands ###
