"""Add keywords to Publication

Revision ID: 702dabd3b4f0
Revises: d5fc6e6ef080
Create Date: 2026-07-27 16:54:44.016036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702dabd3b4f0'
down_revision: Union[str, Sequence[str], None] = 'd5fc6e6ef080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('keywords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'keywords')
    # ### end Alembic commands ###
