"""create funding_opportunities table

Revision ID: a5ec726586f7
Revises: 4f34d4c62888
Create Date: 2026-07-16 19:57:44.799059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ec726586f7'
down_revision: Union[str, Sequence[str], None] = '4f34d4c62888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('agency', sa.String(length=255), nullable=False),
    sa.Column('research_area', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('funding_amount', sa.Float(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('eligibility', sa.Text(), nullable=False),
    sa.Column('application_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_opportunities_id'), 'funding_opportunities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funding_opportunities_id'), table_name='funding_opportunities')
    op.drop_table('funding_opportunities')
    # ### end Alembic commands ###
