"""Add Grant Matching Workflow tables and columns

Revision ID: d5fc6e6ef080
Revises: 
Create Date: 2026-07-27 16:24:52.711424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fc6e6ef080'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grant_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('funding_opportunity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['funding_opportunity_id'], ['funding_opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grant_tracking_funding_opportunity_id'), 'grant_tracking', ['funding_opportunity_id'], unique=False)
    op.create_index(op.f('ix_grant_tracking_id'), 'grant_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_grant_tracking_user_id'), 'grant_tracking', ['user_id'], unique=False)
    op.add_column('funding_opportunities', sa.Column('min_career_stage', sa.String(length=100), nullable=True))
    op.add_column('funding_opportunities', sa.Column('institution_type', sa.String(length=100), nullable=True))
    op.add_column('funding_opportunities', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('funding_opportunities', sa.Column('min_amount', sa.Integer(), nullable=True))
    op.add_column('funding_opportunities', sa.Column('max_amount', sa.Integer(), nullable=True))
    op.add_column('funding_opportunities', sa.Column('deadline_date', sa.DateTime(), nullable=True))
    op.add_column('research_profiles', sa.Column('career_stage', sa.String(length=100), nullable=True))
    op.add_column('research_profiles', sa.Column('institution_type', sa.String(length=100), nullable=True))
    op.add_column('research_profiles', sa.Column('region', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_profiles', 'region')
    op.drop_column('research_profiles', 'institution_type')
    op.drop_column('research_profiles', 'career_stage')
    op.drop_column('funding_opportunities', 'deadline_date')
    op.drop_column('funding_opportunities', 'max_amount')
    op.drop_column('funding_opportunities', 'min_amount')
    op.drop_column('funding_opportunities', 'region')
    op.drop_column('funding_opportunities', 'institution_type')
    op.drop_column('funding_opportunities', 'min_career_stage')
    op.drop_index(op.f('ix_grant_tracking_user_id'), table_name='grant_tracking')
    op.drop_index(op.f('ix_grant_tracking_id'), table_name='grant_tracking')
    op.drop_index(op.f('ix_grant_tracking_funding_opportunity_id'), table_name='grant_tracking')
    op.drop_table('grant_tracking')
    # ### end Alembic commands ###
