"""add_notification_preferences

Revision ID: e2f8c145325c
Revises: 702dabd3b4f0
Create Date: 2026-08-19 23:14:53.217702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f8c145325c'
down_revision: Union[str, Sequence[str], None] = '702dabd3b4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patents', sa.Column('abstract', sa.Text(), nullable=True))
    op.add_column('patents', sa.Column('patent_classification', sa.String(length=255), nullable=True))
    op.add_column('patents', sa.Column('citation_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('patents', sa.Column('cluster_label', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('notification_preferences', sa.String(length=500), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_preferences')
    op.drop_column('patents', 'cluster_label')
    op.drop_column('patents', 'citation_count')
    op.drop_column('patents', 'patent_classification')
    op.drop_column('patents', 'abstract')
    # ### end Alembic commands ###
