/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTrendsRouteImport } from './routes/_app.trends'
import { Route as AppTechnologyRouteImport } from './routes/_app.technology'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppSavedRouteImport } from './routes/_app.saved'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppPatentsRouteImport } from './routes/_app.patents'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppInoovationScoreRouteImport } from './routes/_app.inoovation-score'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppFundingRouteImport } from './routes/_app.funding'
import { Route as AppCommercializationRouteImport } from './routes/_app.commercialization'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAssistantRouteImport } from './routes/_app.assistant'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppTechnologyRoute = AppTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPatentsRoute = AppPatentsRouteImport.update({
  id: '/patents',
  path: '/patents',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppInoovationScoreRoute = AppInoovationScoreRouteImport.update({
  id: '/inoovation-score',
  path: '/inoovation-score',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppFundingRoute = AppFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => AppRoute,
} as any)
const AppCommercializationRoute = AppCommercializationRouteImport.update({
  id: '/commercialization',
  path: '/commercialization',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/assistant': typeof AppAssistantRoute
  '/calendar': typeof AppCalendarRoute
  '/commercialization': typeof AppCommercializationRoute
  '/funding': typeof AppFundingRoute
  '/help': typeof AppHelpRoute
  '/inoovation-score': typeof AppInoovationScoreRoute
  '/messages': typeof AppMessagesRoute
  '/notifications': typeof AppNotificationsRoute
  '/patents': typeof AppPatentsRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/technology': typeof AppTechnologyRoute
  '/trends': typeof AppTrendsRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/assistant': typeof AppAssistantRoute
  '/calendar': typeof AppCalendarRoute
  '/commercialization': typeof AppCommercializationRoute
  '/funding': typeof AppFundingRoute
  '/help': typeof AppHelpRoute
  '/inoovation-score': typeof AppInoovationScoreRoute
  '/messages': typeof AppMessagesRoute
  '/notifications': typeof AppNotificationsRoute
  '/patents': typeof AppPatentsRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/saved': typeof AppSavedRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/technology': typeof AppTechnologyRoute
  '/trends': typeof AppTrendsRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/commercialization': typeof AppCommercializationRoute
  '/_app/funding': typeof AppFundingRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/inoovation-score': typeof AppInoovationScoreRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/patents': typeof AppPatentsRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/technology': typeof AppTechnologyRoute
  '/_app/trends': typeof AppTrendsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/analytics'
    | '/assistant'
    | '/calendar'
    | '/commercialization'
    | '/funding'
    | '/help'
    | '/inoovation-score'
    | '/messages'
    | '/notifications'
    | '/patents'
    | '/projects'
    | '/reports'
    | '/saved'
    | '/search'
    | '/settings'
    | '/team'
    | '/technology'
    | '/trends'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/analytics'
    | '/assistant'
    | '/calendar'
    | '/commercialization'
    | '/funding'
    | '/help'
    | '/inoovation-score'
    | '/messages'
    | '/notifications'
    | '/patents'
    | '/projects'
    | '/reports'
    | '/saved'
    | '/search'
    | '/settings'
    | '/team'
    | '/technology'
    | '/trends'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/analytics'
    | '/_app/assistant'
    | '/_app/calendar'
    | '/_app/commercialization'
    | '/_app/funding'
    | '/_app/help'
    | '/_app/inoovation-score'
    | '/_app/messages'
    | '/_app/notifications'
    | '/_app/patents'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/saved'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/technology'
    | '/_app/trends'
    | '/_app/users'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trends': {
      id: '/_app/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/technology': {
      id: '/_app/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof AppTechnologyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patents': {
      id: '/_app/patents'
      path: '/patents'
      fullPath: '/patents'
      preLoaderRoute: typeof AppPatentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inoovation-score': {
      id: '/_app/inoovation-score'
      path: '/inoovation-score'
      fullPath: '/inoovation-score'
      preLoaderRoute: typeof AppInoovationScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/funding': {
      id: '/_app/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof AppFundingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commercialization': {
      id: '/_app/commercialization'
      path: '/commercialization'
      fullPath: '/commercialization'
      preLoaderRoute: typeof AppCommercializationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCommercializationRoute: typeof AppCommercializationRoute
  AppFundingRoute: typeof AppFundingRoute
  AppHelpRoute: typeof AppHelpRoute
  AppInoovationScoreRoute: typeof AppInoovationScoreRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPatentsRoute: typeof AppPatentsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTechnologyRoute: typeof AppTechnologyRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCommercializationRoute: AppCommercializationRoute,
  AppFundingRoute: AppFundingRoute,
  AppHelpRoute: AppHelpRoute,
  AppInoovationScoreRoute: AppInoovationScoreRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPatentsRoute: AppPatentsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSavedRoute: AppSavedRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTechnologyRoute: AppTechnologyRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
